// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "UIKit App",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "UIKit App",
            targets: ["AppModule"],
            bundleIdentifier: "com.ankushgirotra.uikitapp",
            teamIdentifier: "QCLBA324PV",
            displayVersion: "0.1",
            bundleVersion: "2",
            appIcon: .placeholder(icon: .gamepad),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .utilities
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
